### ISSUE TITLE
Trying to add some features

### ISSUE THREAD

**Issue by ghost** [iFaxity/SoundCloud.Desktop#2]
Hello! I'm new to C# but I've been coding in HTML, CSS, JavaScript, and PHP for a while now. I downloaded SoundStreamer and started to work on it but when I went to build it I got an error: 
**"Could not copy the file {LOCAL_PATH}\SoundStreamer\Bass\x64\bass.dll"**
and
**"Could not copy the file {LOCAL_PATH}\SoundStreamer\Bass\x86\bass.dll"**
Is this a mistake I made when downloading the code? Or is this a real issue? Thought I should bring it up just in case, I hope to temporarily fix it by getting the dll from either the download of the actual program or from bass.NET.
- Timothy

**Comment by Tbonerichards** [comment]
My bad I think I'm having a problem on my end, sorry for the mix up!

**Comment by ghost** [comment]
Okay well, I thought it was an issue on my end, I got the dll error to stop but now I'm getting this while running the installer:

![image](https://cloud.githubusercontent.com/assets/10431151/11485776/040df2fe-976a-11e5-8993-cd987d3d9bfe.png)

**Comment by iFaxity** [comment]
The first one is not a problem on my end. It seems that either the files in the folder Bass is missing. Or you have invalid folder permissions when debugging.

The other is a prolem with the installer. I'll help you fix this. But i will need more detailed information while you're debugging. Although this could be easily fixed by wrapping the Exit() method with a try catch block (which i'm fixing tomorrow).

The error is probably occuring because the installed failed to install the program.
Also i know the installer is sort of unstable. I made the installer in a rush. Now i'm polishing it and with more options.

I'm grateful that you've taken an interest to the application.

**Comment by ghost** [comment]
Alright, I'm not sure what details you want from the debug so here is the output it let me copy. 

System.ComponentModel.Win32Exception was unhandled
  ErrorCode=-2147467259
  HResult=-2147467259
  Message=The system cannot find the file specified
  NativeErrorCode=2
  Source=System
  StackTrace:
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at Installer.MainWindow.Exit() in C:\Users\Timothy\Documents\GitHub\SoundStreamer\Installer\MainWindow.xaml.cs:line 126
       at Installer.MainWindow.<.ctor>b__3_2(Object sender, RoutedEventArgs e) in C:\Users\Timothy\Documents\GitHub\SoundStreamer\Installer\MainWindow.xaml.cs:line 68
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at Installer.App.Main() in C:\Users\Timothy\Documents\GitHub\SoundStreamer\Installer\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by ghost** [comment]
Also when I run the installer it gives me a popup that says the install was successful.

**Comment by iFaxity** [comment]
Yeah, i changed server host so it might be that the installer can't download the files. I'll post a reply tomorrow.

**Comment by ghost** [comment]
Okay, thank you.

**Comment by iFaxity** [comment]
I've found the problem and it resides with the server. I will work my way of fixing this and i will close this issue once this is done. 

Edit: Bug fixed. Publishing a crash proof installer by next week.
